apiVersion: v1
kind: Pod
metadata: 
  name: pvpod
spec:
  containers: 
    - name: pv-container
      image: tasdidur/test-ingress
      volumeMounts:
      - mountPath: /home/
        name: pvc
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: pvc-name