apiVersion: v1
kind: Pod
metadata: 
  name: pvpod2
spec:
  containers: 
    - name: pv-container2
      image: tasdidur/test-ingress
      volumeMounts:
      - mountPath: /home/
        name: pvc
  nodeSelector:
    name: node1
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: pvc-name