apiVersion: v1
kind: Pod
metadata: 
  name: pod3
spec:
  containers: 
    - name: pod3-container
      image: tasdidur/test-ingress
      volumeMounts:
      - mountPath: /home/mount-here
        name: mounted-volume
  volumes:
    - name: mounted-volume
      persistentVolumeClaim:
        claimName: pvc-name