apiVersion: v1
kind: Pod
metadata: 
  name: pod4
spec:
  containers: 
    - name: pod4-container
      image: tasdidur/test-ingress
      volumeMounts:
      - mountPath: /home/mount-there
        name: mounted-volume
  volumes:
    - name: mounted-volume
      persistentVolumeClaim:
        claimName: clone-pvc