apiVersion: v1
kind: Pod
metadata: 
  name: pod5
spec:
  containers: 
    - name: pod5-container
      image: tasdidur/test-ingress
      volumeMounts:
      - mountPath: /home/mount-ekhane
        name: mounted-volume
  volumes:
    - name: mounted-volume
      persistentVolumeClaim:
        claimName: pvc-local-name