apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-name
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt
  nodeAffinity:
   required:
    nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [volcls-worker,volcls-worker2]