apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc-local-name
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi