apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: clone-pvc
  namespace: default
spec: 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc-name